### PR TITLE
Additional PermissionHandler Features

### PR DESCRIPTION
**Pull request by Flo0205**
I wanted to change my permissionfile with plugins.
So I added this to Synapse. So here you go!

### CODE REVIEW

**Comment by AlmightyLks** [comment]
Tested?

**Comment by Flo0205** [comment]
It worked on my machine. XD

**Comment by GrafDimenzio** [comment]
I think it would be easier to add a UpdateGroup() method instead of so many small methods

**Comment by Flo0205** [comment]
Ok. I‘ll do This later

**Comment by Flo0205** [comment]
Somehow I wasn't able to make it working again, so I told Mika how to do it.

Here is his request:
https://github.com/SynapseSL/Synapse/pull/72

**Pull request closed without merging**
