### PR TITLE
Added GetAllGroups

### PR DESCRIPTION
**Pull request by Mika-Westphal**

### CODE REVIEW

**Comment by AlmightyLks** [comment]
I mean, I am certain that it has a reason why `Groups` is an internal readonly dictionary.
Simply making a getter-like method means giving access to it and allowing it to be manipulated in a `public` scope

**Comment by AlmightyLks** [comment]
If Dimenzio prefers it to be internal, but also somewhat of accessibility, make it return a deep-copy - My two cents

**Comment by Mika-Westphal** [comment]
Well, I understand you point but how do you want to edit a read only object?

**Comment by AlmightyLks** [comment]
The readonly modifier means you can just not overwrite the collection with another collection, but you can still remove and add elements from/to the dictionary (unlike an IReadOnlyDictionary)

**Comment by Mika-Westphal** [comment]
Ok... I see what you mean. I overwork it

**Comment by Mika-Westphal** [comment]
Now it should work because you can now only change the SynapseGroups and not the dictionary itself

**Comment by Mika-Westphal** [comment]
It is not GetAllGroups. It is now Groups

**Pull request merged**
