### PR TITLE
Fix some Bug And Add new Event 

### PR DESCRIPTION
**Pull request by warquys**
Add the possibility to use the RemoteKeyCard on the locker.
> New Event when you try to open a Locker.
> I add a Locker & LockerChamber Class And a new Enum for type of Locker.
> I add a new extension for get the Locker.

Fix the AutoFF at the End of the Game.
> I have patched the method to know if it was a FF.
> This means that the verification is done from the event.
> This maybe have broken the automatic FF warning.
> PlayerDamageEvent is call even if it is not allowed !
This is also fixed the fact that the custom class could not attack the other player of the same type role.

The jail bug is fix.
> The bug which caused the player to cant get back he ammo has been fixed.
> But i find a new Bug, the player does not receive the correct attachments for these weapons.

### CODE REVIEW

**Comment by warquys** [comment]
I took the wrong branch !

**Comment by Polyfish0** [comment]
Sorry that you had to wait so long for an answer. I will later look at your changes!

**Comment by warquys** [comment]
no problem.

**Comment by Polyfish0** [comment]
Hey, sorry for the delay of 7 days. I _maybe_ forgot the PR because of school.
It's fine. Have a nice day

**Pull request merged**
