### PR TITLE
Event & ctrl Scp & Scp Talk & Fix Round End & KeyBind

### PR DESCRIPTION
**Pull request by warquys**

### CODE REVIEW

**Comment by warquys** [comment]
Error can be created when i do the fusion

**Comment by warquys** [comment]
I did not make these last 3 patches, they are necessary to finish the controllers:
TantrumCoolDown
CurentBlinkCooldown
Observer

maby i add them latter

I did not put anything in the controller of 939 and it will be necessary to add elements in those of 106, I would do it too if I have time.

**Comment by warquys** [comment]
I add a keybind class to a better handle of the key press, i use it to readd the scp chat proximity.
Note: Use V to switch to roximity chat to scp chat

**Comment by GrafDimenzio** [comment]
I haven't looked into the events yet, but I recommend splitting a PR like this into at least 2. The Events and KeyBind System are 2 completely different things and since you made only one PR for both I can't just check if the event works and merge them into the project but rather I now also have to checkout the entire KeyBind System.
Also, Please test your events if they are properly working and not only add a lot of code and hope that it works because Spoiler: a lot of the NW Events aren't working as you would assume

**Comment by warquys** [comment]
ok

**Comment by GrafDimenzio** [comment]
You don't have to close the PR

**Comment by warquys** [comment]
idk how to split a PR in two.

**Comment by GrafDimenzio** [comment]
That was just for the future, I'm almost done reviewing this PR

**Comment by warquys** [comment]
Ok

**Comment by warquys** [comment]
I would like to add a last event which is when the player speaks I test it tomorrow and I add it (if scp sl is up to date because my server is in 12.0.1 and my games in 12.0.0)

**Comment by warquys** [comment]
I prepared new branch on my side, I fixed and tested that it works well!

I fixed the abstractRoles
I created a HintManager that I want to use to reintegrate unity for custom roles
I fixed the SynapseItem

I created pull requests one by one after their merges, their refusal or revew

**Comment by warquys** [comment]
However I have it is based on each other because I needed a version of Synapse with all these Updates
So I have to wait for you to accept this one

**Pull request merged**
