### PR TITLE
Readme Created for the synapse3 branch.

### PR DESCRIPTION
**Pull request by BenjaminDaBirb**
Contains a warning for server owners to not use it as there will be some complications, since the Synapse3 Source Code isn't complete and things are yet to be added/implemented and bugs yet to be fixed.

[Link to the Readme](https://github.com/BenjaminDaBirb/Synapse3/blob/synapse3/README.md)

### CODE REVIEW

**Comment by GrafDimenzio** [comment]
Are you serious right now? Are you Just adding anything to get the discord role? I highly doubt that any hoster that doesnt know what Synapse is would Go Out of their way to Compile source Code of another Branch and expect it to Work. Also i dont know how you did it but this pr also contains all commits again from the previous pr If you create a pr that is specific only about the readme then it should be only about the readme

**Comment by BenjaminDaBirb** [comment]
@GrafDimenzio If it were for the discord role, i would be making random commits to prove that i contribute. Please think atleast 10 times before you say anything.

**Comment by BenjaminDaBirb** [comment]
> Are you serious right now? Are you Just adding anything to get the discord role? I highly doubt that any hoster that doesnt know what Synapse is would Go Out of their way to Compile source Code of another Branch and expect it to Work. Also i dont know how you did it but this pr also contains all commits again from the previous pr If you create a pr that is specific only about the readme then it should be only about the readme

Just BECAUSE i asked you if i can get the role, doesn't mean I will do anything to get it. I am just normally asking if i can get that. What's wrong with it?

And this Readme PR was completely unrelated to the discord role.

**Comment by MineTech13** [comment]
5 File Changes for a Readme Creation kinda sus

**Comment by BenjaminDaBirb** [comment]
> 5 File Changes for a Readme Creation kinda sus

I was editing the readme to make it look better.

**Pull request closed without merging**
