### PR TITLE
Added a map event for when a generator is engaged

### PR DESCRIPTION
**Pull request by Bonjemus**
_The title is self-explainatory._

### CODE REVIEW

**Comment by Bonjemus** [comment]
I changed the event : it will now be called whenever the server changes the flag of the generator. The event's argument will now include the new flag.

**Comment by GrafDimenzio** [comment]
Why didn't you implement something like allow so that plugins can prevent it, and also I can't accept the ChangeRoleAtPosition changes:

1. You break every plugin using it like this
2. The Healtstat has a method to reset itself, so this code is more complicated than it needs to be

**Comment by GrafDimenzio** [comment]
Also don't push something into master

**Comment by Bonjemus** [comment]
I fixed everything I think except this incorrect formatting stuff because I have no idea what you're reffering to, could you explain please ?

**Comment by GrafDimenzio** [comment]
You did add another parameter but the plugins are build to only give 1 this throws a lot of errors also you somehow messed up the MapEvent file for github so you have to fix it before I merge it and the patch is still not formatted and I'm still not sure if the Event is really needed with this implementation

**Comment by Bonjemus** [comment]
Another parameter to what ?
"patch is still not formatted" what does this mean ?

**Comment by GrafDimenzio** [comment]
scroll down https://github.com/SynapseSL/Synapse/pull/101/files

**Comment by Bonjemus** [comment]
:(

**Comment by GrafDimenzio** [comment]
This was automatically closed with the deletion of the old dev branch. However the same 3 points are still valid why I don't accept it:
1. You deleted the MapEvent File and added it again which causes Merge problems
2. Your patch still looks weird (Although this isn't that important)
3.  The Implementation of this Event looks really cheap and the implementation of Allow will most likely cause confusion
```cs
if (this.ActivationReady)
{
	if (flag && !this.Engaged)
	{
		this.Engaged = true;
		this.Activating = false;
		return;
	}
	this._currentTime += Time.deltaTime;
}
```
This is the code responsible for engaging the Generator and you just prevent it from being Engaged but at the same time it will also be deactivated and therefore it can't be engaged again unless it is specifically enabled by a Plugin which is in my opinion an unexpected behavior for the developers. It would be more natural to call the event every frame again as long as allow is false or a plugin resets the time of the generator

**Comment by Bonjemus** [comment]
So if I got it correctly, I should re-enable the generator and reset it's timer as well, if Allow = false, right ?
(Also, I didn't want to implement Allow at first because I thought just like you that it's implementation could cause problems with the game.)

And the event might seem "cheap" but I do need it and others might too one day or another.

**Comment by GrafDimenzio** [comment]
With cheap I meant it cause a lot of problems since it's the easiest solution to patch that method and not the Update method. I thought at first this will create a lot of problems but after looking a bit more into the game I think it's doesn't cause problems when patched properly (thats why I edited the comment and removed this section). But I didn't mean to disable the timer by Synapse but rather just activating the generator again so a plugin has the option to enable it.

For Example the plugin for some reason sets Allow to false so long until someone used the Command to either let it finally engage or resets the time. In my opinion thats the best solution for the developers

**Pull request closed without merging**
