### PR TITLE
New GetPlayer for the Footprint And Analyze method for the DamageHandler

### PR DESCRIPTION
**Pull request by warquys**

### CODE REVIEW

**Comment by GrafDimenzio** [comment]
I think this is to complicated you mixed the DamageHandler types and Universal Damage Translations and ended up in not having every DamageType I think it would be better to split it up into 2 Enums. It would make it a bit more hard to understand for new developers however it gives you every information that you could want

**Comment by warquys** [comment]
ok.

**Comment by warquys** [comment]
I don't understand you just integrated a damagetype enum. Do I have to do two enums or only one enum?

**Comment by GrafDimenzio** [comment]
I moved the second one into the first one but i'm still finding them out on 2 different ways depending on if they are a universal damage or a other one. After thinking about it longer I thought this would be better

**Comment by warquys** [comment]
So I close the request ?

**Pull request closed without merging**
